import {IProject} from '../../../app/services/api/todoist/interfaces/project';

export const mockProjectsList: IProject[] = [
  {
    color: 'charcoal',
    comment_count: 0,
    id: '2323562838',
    is_favorite: false,
    is_inbox_project: true,
    is_shared: false,
    is_team_inbox: false,
    name: 'Inbox',
    order: 0,
    parent_id: null,
    url: 'https://todoist.com/showProject?id=2323562838',
    view_style: 'list',
  },
  {
    color: 'sky_blue',
    comment_count: 0,
    id: '2323634645',
    is_favorite: false,
    is_inbox_project: false,
    is_shared: false,
    is_team_inbox: false,
    name: 'Morning tasks',
    order: 4,
    parent_id: null,
    url: 'https://todoist.com/showProject?id=2323634645',
    view_style: 'list',
  },
  {
    color: 'grape',
    comment_count: 0,
    id: '2323634802',
    is_favorite: false,
    is_inbox_project: false,
    is_shared: false,
    is_team_inbox: false,
    name: 'School',
    order: 5,
    parent_id: null,
    url: 'https://todoist.com/showProject?id=2323634802',
    view_style: 'list',
  },
  {
    color: 'lime_green',
    comment_count: 0,
    id: '2323658588',
    is_favorite: false,
    is_inbox_project: false,
    is_shared: false,
    is_team_inbox: false,
    name: 'Work',
    order: 6,
    parent_id: null,
    url: 'https://todoist.com/showProject?id=2323658588',
    view_style: 'list',
  },
  {
    color: 'orange',
    comment_count: 0,
    id: '2323795048',
    is_favorite: false,
    is_inbox_project: false,
    is_shared: false,
    is_team_inbox: false,
    name: 'Weekend',
    order: 7,
    parent_id: null,
    url: 'https://todoist.com/showProject?id=2323795048',
    view_style: 'list',
  },
  {
    color: 'berry_red',
    comment_count: 0,
    id: '2328357844',
    is_favorite: false,
    is_inbox_project: false,
    is_shared: false,
    is_team_inbox: false,
    name: 'Tttt',
    order: 8,
    parent_id: null,
    url: 'https://todoist.com/showProject?id=2328357844',
    view_style: 'list',
  },
];
